### ISSUE TITLE
Formatting of `<pre>` and `<code>` elements leads to poor readability

### ISSUE THREAD

**Issue by KathyReid** [MycroftAI/docs-rewrite#64]
## Description of Issue in object-deviation format

The `docs-rewrite` repo content is authored in the MarkDown markup language, and is then consumed by WordPress, where a plugin renders the MarkDown into HTML, which is styled using the WordPress Salient Theme styling. 

Unfortunately, some elements like `<pre>` and `<code>` are difficult to read as shown in the screenshots below. 

### Current CSS rules used to style these elements

```
pre, code {
    font-family: 'Ubuntu Mono', monospace;
    display: inline;
}
```

## Suggested solution

Improve the CSS styling for these elements so that they are more readable

## Screenshots of the problem 

![screenshot from 2018-05-16 01-22-03](https://user-images.githubusercontent.com/114158/40067449-82ff759e-58a9-11e8-9604-d3da52f8dfa4.png)

![screenshot from 2018-05-16 01-09-06](https://user-images.githubusercontent.com/114158/40067451-83415608-58a9-11e8-8080-9882b4b2c741.png)

![screenshot from 2018-05-16 01-07-41](https://user-images.githubusercontent.com/114158/40067452-8383982e-58a9-11e8-8e2e-ab1069e8cb8e.png)

**Comment by KathyReid** [comment]
This was sent out for feedback; feedback gratefully received. Implemented into production but keeping this Issue open because there's a couple of edge cases I'm still not happy with: 

* in a `pre` block, if the text width is wider than the `viewport`, there is no scroll mechanism, so on a narrow `viewport`, such on a mobile phone, then the right hand side of the `pre` block is truncated and there's no way to see it without viewing source. 

* On a mobile device, I'm used to being able to "pinch and zoom" to increase or decrease the size of the text. The Salient Theme does not appear to support "pinch and zoom" but there are several blog posts around which talk about "pinch and zoom" support in WordPress in general: 
* https://gist.github.com/Garconis/34b6be24ee644c024663ef1d2e11e2bb

NEXT ACTION: Look at `pre` block overflow and pinch and zoom

**Comment by KathyReid** [comment]
I've implemented a code change to the CSS to allow for horizontal scrolling. It still doesn't fix the pinch and zoom issue, but it makes `pre` elements viewable on small-viewport sizes. 

```css
/* Styling for code blocks */

pre code {
    padding: 0%;
}

pre, code {
    font-family: 'Ubuntu Mono', monospace;
    font-weight: lighter;
    font-size: 1.05em;
    background-color: #f0f0f0;
}

pre {
    border: 1px dotted black;
    padding: 1.2%;
    display: inline-block;
    margin-bottom: 1.5em;
    overflow: auto;
    word-wrap: break-word;
    white-space: pre-wrap;
    max-width: 100%;
}

code {
    padding: 0.4%;
    display: inline;
}
```
